/**
 * Copies the tested kit sources in design-kit/kit into lib/design/kitFiles.ts,
 * so the server can add them to a project without reading files at run time.
 *
 *   npx tsx scripts/gen-kit.mts          (write)
 *   npx tsx scripts/gen-kit.mts --check  (fail if out of date)
 */
import { readdir, readFile, writeFile } from 'node:fs/promises';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const source = path.join(root, 'design-kit', 'kit');
const target = path.join(root, 'lib', 'design', 'kitFiles.ts');

const files: Record<string, string> = {};
for (const name of (await readdir(source)).sort()) {
    files[`src/kit/${name}`] = (await readFile(path.join(source, name), 'utf8')).replace(/\r\n/g, '\n');
}
const output = `/* Generated by scripts/gen-kit.mts from design-kit/kit. Do not edit by hand. */

/** The Fyxable kit, as project files: motion and interface pieces every website and app starts with. */
export const KIT_FILES: Record<string, string> = ${JSON.stringify(files, null, 4)};
`;
if (process.argv.includes('--check')) {
    const current = await readFile(target, 'utf8').catch(() => '');
    if (current !== output) {
        console.error('lib/design/kitFiles.ts is out of date: run npx tsx scripts/gen-kit.mts');
        process.exit(1);
    }
    console.log('kitFiles.ts is up to date');
} else {
    await writeFile(target, output);
    console.log(`wrote ${Object.keys(files).length} kit files to lib/design/kitFiles.ts`);
}
