import type { Reference } from "./references";

/** The library as first condensed (scripts/seed-references.mts): used until the admin changes it. */
export const REFERENCE_SEED: Reference[] = [
  {
    id: "asp-net-core-identity-crm-pattern",
    kind: "blueprint",
    name: "ASP.NET Core Identity CRM Pattern",
    tags: [
      "asp.net core 8",
      "mvc",
      "ef core",
      "sqlite",
      "crm",
      "identity",
      "role based access control",
      "audit logging",
      "anti forgery",
      "lead workflow",
      "rate limiting",
      "swagger",
      "bootstrap 5",
    ],
    points: [
      "Lock application endpoints globally by configuring FallbackPolicy with RequireAuthenticatedUser() in Program.cs, and configure CookieAuthenticationEvents to return 401/403 HTTP status codes on /api routes instead of browser redirects.",
      "Implement consistent row-level authorization via an IAssignable interface and an IQueryable extension method (.ForUser()), constraining queries to AssignedTo == currentUserId for sales executives while allowing managers and admins full team visibility.",
      "Enforce automated entity auditing by intercepting SaveChangesAsync in AppDbContext to record changes on IAuditable entities into AuditLogs, paired with a dedicated AuditService for explicit security events (failed logins, lockouts, conversions).",
      "Centralize core business rules and transactional transitions in CrmService—such as lead conversion into paired Customer and Opportunity records, and email/phone duplicate detection returning 409 Conflict.",
      "Structure layered validation by combining DataAnnotations and custom validation attributes (e.g., NotPastDate, GreaterThan) on FormViewModels, backed by server-side ModelState verification and a uniform ApiBehaviorOptions.InvalidModelStateResponseFactory for API consumers.",
      "Defend spreadsheet exports against CSV and formula injection by prefixing any field starting with '=', '+', '-', or '@' with a single quote character in Csv.cs.",
      "Map enum properties directly to readable string values in AppDbContext using ConfigureConventions (HaveConversion<string>()) to keep raw database rows and audit entries human-readable.",
      "Prove compliance and simplify verification by maintaining an EXPLAIN.md requirement-to-code traceability matrix, providing demo user accounts across each role in SeedData.cs, and documenting API schemas with Swagger.",
    ],
    source: "https://github.com/SkAshraf16/SmartSales",
    addedAt: 1791676800000,
    enabled: true,
  },
  {
    id: "industrial-commercial-equipment-marketing-site-des",
    kind: "design",
    name: "Industrial commercial equipment marketing site design system",
    tags: [
      "next.js 16",
      "tailwind css v4",
      "react 19",
      "b2b manufacturer",
      "commercial kitchen equipment",
      "marketing website",
      "lead generation",
      "motion animations",
      "warm paper palette",
      "editorial industrial",
      "single-table dynamodb",
      "isr catalog",
    ],
    points: [
      "Palette combines warm paper backgrounds (#faf9f5 / #eceae3), deep ink (#16150f / rgb(47,46,46)) for copy, charcoal (#1c1b18) and night (#100f0c) for dark card bands, with an industrial brand yellow (#edcd1f, #d8b80f, #fbf3c4) for accents and text selections.",
      "Typography pairs the Saans or Switzer grotesque sans family (with fallback to Arial/system sans) using tight negative letter-spacing (-0.02em to -0.03em) on headings and balanced text-wrapping across clamp-based hero scales.",
      "The home page layout stacks a pinned hero beneath a rising curved sheet (rounded-t-[2rem] sm:rounded-t-[2.5rem] in paper tone with heavy upward shadow) that leads into client logos, product showcases, process journey, and testimonials.",
      "Grid rhythm alternates between 2-column feature narratives with alternating text/media orders (lg:order-1 / lg:order-2) and 4-column carousel/card grids (min-h-[26rem]) framed by subtle hairline borders (#d6d2c7) and a 64px background grid utility.",
      "Container corners scale from rounded-3xl on content cards to rounded-[1.75rem] on image wrappers and rounded-full on chips and pill buttons, avoiding razor-sharp industrial edges in favor of warm precision.",
      "Card lighting uses dual-layer soft elevation (0 2px 6px rgba(28,27,27,0.05) combined with 0 18px 40px -16px rgba(28,27,27,0.18)) paired with inner rings (ring-1 ring-inset ring-white/10) over bottom-to-top gradient overlays on dark imagery.",
      "Motion relies on Lenis smooth-scrolling, cubic-bezier(0.16, 1, 0.3, 1) ease-out entry reveals, looped horizontal marquees with hover-pause states, and shimmer skeleton transforms that disable gracefully under reduced motion.",
      "Imagery pairs warm, documentary-style photography of workshop fabrication, stainless steel kitchen passes, and real client environments with graceful placeholder fallbacks when product images are missing.",
    ],
    source: "https://github.com/Prateek22672/veecos",
    addedAt: 1791676800000,
    enabled: true,
  },
  {
    id: "hireview-editorial-ai-recruiting-interface",
    kind: "design",
    name: "HireView editorial AI recruiting interface",
    tags: [
      "ai interview",
      "recruitment platform",
      "next.js",
      "fastapi",
      "tailwind css",
      "warm editorial",
      "botanical vector accents",
      "slate sidebar",
      "proctoring dashboard",
      "candidate assessment",
      "zustand",
    ],
    points: [
      "Establish a warm, literary foundation using Switzer for clean geometric headings paired with Inter for dense tabular body text, avoiding cold tech-blue defaults.",
      "Ground application canvases on surface warm off-white (#faf9f7) with near-black ink (#1a1a1a) typography, accented by terracotta-coral (#c96442) for highlights and slate-900 (#111827) for navigation sidebars.",
      "Structure candidate and recruiter flows systematically: authentication with botanical line-art hero headers, job creation wizards, RAG-driven candidate shortlists, live interview proctoring panes, and PDF report downloads.",
      "Adopt soft functional badges with subtle tints: emerald (#22c55e) for success and strong-hire, amber (#f59e0b) for warnings, crimson (#ef4444) for alerts, and violet (#8b5cf6) for AI-derived insights.",
      "Employ ultra-light botanical or architectural SVG stroke motifs (#3a6b1e at 0.1 to 0.3 opacity) in login banners and onboarding cards to soften clinical interview tooling.",
      "Apply conservative structural radii using rounded-lg (8px) for buttons or input fields and rounded-xl (12px) for card containers with thin 1px warm-border frames (#e8e4e0).",
      "Utilize low-elevation diffusion shadows (0 1px 3px rgba(0,0,0,0.06)) on flat panels, elevating to 0 4px 16px rgba(0,0,0,0.10) exclusively for modals, dropdowns, and active cards.",
      "Restrain UI motion to swift, imperceptible utility transitions: 150ms ease-out opacity shifts, 200ms fade-ins, and 6px subtle upward translates (slide-up 250ms) during view rehydration.",
    ],
    source: "https://github.com/Prateek22672/hireview",
    addedAt: 1791676800000,
    enabled: true,
  },
  {
    id: "luxury-eb-5-real-estate-investment-editorial",
    kind: "design",
    name: "Luxury EB-5 Real Estate Investment Editorial",
    tags: [
      "react",
      "vite",
      "tailwind css",
      "framer-motion",
      "gsap",
      "real estate",
      "eb-5 investment",
      "editorial design",
      "warm dark luxury",
      "interactive cards",
      "parallax hero",
      "text cycle",
      "financial landing page",
    ],
    points: [
      "Structure pages in an editorial eight-part sequence: full-bleed immersive hero, company ethos with roman-numeral pillar cards, multi-stage linear roadmap, application criteria, property catalog with inline image sliders, layered benefit peek-cards, strategic partnerships, and an accordion FAQ footer.",
      "Pair a high-contrast serif for headings and expressive accents with a neutral grotesque sans-serif for body copy and an uppercase monospaced face for tracking tags, counters, and status badges (e.g., Instrument Serif, Outfit or Syne, and Fira Code).",
      "Build palettes on warm bone/cream surfaces (#F4F2EC, #E8E5D8) contrasted against obsidian darks (#070707, #0E0E0E, #141414) and muted metallic gold accents (#C9A96E / #C4A97C), using moss green (#8A9A6A) and stone (#8A8578) for secondary tones.",
      "Enforce generous vertical breathing room with mobile paddings of 5rem (80px) and desktop sections extending up to 9rem (144px), framing card containers with generous 12px to 20px border radii.",
      "Implement mouse-driven cursor parallax on desktop heroes with lerped coordinate tracking, scaling background imagery (scale ~1.06) while nudging foreground typography forward to produce layered spatial depth.",
      "Incorporate cycling animated italic text using spring-based width tracking and vertical translates with Gaussian blur filtering (blur-12px to blur-0) during word swaps.",
      "Replace horizontal scrolling mechanisms on mobile devices with touch-friendly step-by-step switcher controls and animated step trackers to preserve vertical page flow.",
      "Deliver luxury tactile depth through 40px subtle radial dot grids, delicate 1px hairline dividers with gold gradient center-fades, and a sticky bottom backdrop-blur gradient overlay (10px blur with mask falloff).",
    ],
    source: "https://github.com/Prateek22672/Forterra-Developers",
    addedAt: 1791676800000,
    enabled: true,
  },
  {
    id: "kinetic-brutalist-agency-portfolio-system",
    kind: "design",
    name: "Kinetic Brutalist Agency Portfolio System",
    tags: [
      "next.js",
      "gsap",
      "scrolltrigger",
      "lenis",
      "marketing agency",
      "interactive portfolio",
      "dark mode",
      "kinetic typography",
      "fanned cards",
      "custom cursor",
      "full-page pinned scroll",
      "smooth scrolling",
    ],
    points: [
      "Establish the layout through full-viewport pinned panels stacked via ScrollTrigger, transitioning with an asymmetrical 25-degree rotation sweep anchored from bottom-left.",
      "Pair Syne for bold display typography, Space Grotesk for subheadings and buttons, Outfit for readable body text, and Fira Code for uppercase, tracked-out metadata tags.",
      "Structure the story arc sequentially: light high-contrast Hero (#ffffff with #111111 text), followed by dark story panels (#050505 to #111111) for About, Services, Packages, Process, Clients, and Contact.",
      "Anchor the color palette in deep darks (#000000, #050505, #0c0c0c, #111111, #151515, #222222) accented by warm acid orange (#ee7435, #ff935c, #d95f22), cobalt blue (#0d43fe), and off-whites (#f5f5f5, #f8f8f8, #ececec).",
      "Format section pre-headers with a 40px single-pixel horizontal rule, tracked mono uppercase, and numeric step markers (e.g., '03 — Our Services') in accent orange.",
      "Employ custom dual-cursor navigation (10px solid center dot with mix-blend-mode: difference and an easing 40px follower ring with 0.4 opacity border) while suppressing system cursors across all interactives.",
      "Drive section transitions and text reveals with GSAP split-line text translations (y: 110% to 0% with expo.out) and scrubbed character-by-character color illumination on scroll.",
      "Design interactive card showcases using dynamic spatial arrangements, toggling between an arc fan (-30 to +30 degrees rotZ, wide x-offsets) and an offset deck stack (-10 to +10 degrees rotZ) with perspective tilts on hover.",
      "Enrich dark backgrounds using ultra-subtle 4% fractal SVG noise overlays, faint 80px by 80px linear grid overlays, and translucent, oversized display typography running off-canvas.",
    ],
    source: "https://github.com/Prateek22672/krisha-ai",
    addedAt: 1791676800000,
    enabled: true,
  },
  {
    id: "dark-industrial-smart-parking-interface-system",
    kind: "design",
    name: "Dark Industrial Smart Parking Interface System",
    tags: [
      "react native",
      "expo",
      "nativewind",
      "tailwind css",
      "smart parking",
      "geofencing",
      "dark mode",
      "realtime dashboard",
      "slot reservation",
      "firebase",
      "mobile ui",
      "monochrome",
    ],
    points: [
      "Ground the interface in high-contrast deep blacks (#000000 base, #080808 to #111111 for cards and controls) paired with stark #FFFFFF and muted metallic accents (#312651, #444262, #83829A, and #FF7754 for alerts).",
      "Pair geometric sans typography (Switzer in Regular, Medium, Semibold, and Bold; or DM Sans variants) using tight uppercase section kickers with heavy letter spacing (+2) over massive 34px display titles (-1 letter spacing).",
      "Structure onboarding and entry flows around centered, vertical stacks featuring a signature 56x56 rounded brand mark tile, crisp multi-line headlines, isolated input groups, and bottom-anchored actions.",
      "Lay out slot grids and vehicle selectors using square-proportioned micro-tiles (62x62) with 14px corner radii, switching dynamically between locked low-contrast borders (#1A1A1A) and high-contrast selected states (#FFFFFF surface with #000000 glyphs).",
      "Apply precise input field geometry with 16px corner radii, 1px subtle borders (#1C1C1C resting, #FFFFFF focused), and muted placeholder tones (#2A2A2A) accented by minimal vector iconography.",
      "Implement motion using parallel spring-driven reveals: entrances slide up by 14-18px over 380-480ms with native timing, while tile interactions trigger an instant 0.88 scale squish followed by a high-tension rebound.",
      "Enforce modal and bottom sheet presentation via spring physics rising from off-screen (300px offset) to overlay the darker workspace for time-selection and confirmation flows.",
      "Elevate the industrial aesthetic through discrete subtle elevation (elevation 2 to 5 with black opacity at 0.25) and state-specific iconography (bicycles for 2-wheelers, vehicle silhouettes for 4-wheelers, and padlocks for occupied nodes).",
    ],
    source: "https://github.com/Prateek22672/smart-parking-system",
    addedAt: 1791676800000,
    enabled: true,
  },
  {
    id: "voice-ai-platform-developer-dashboard-design-syste",
    kind: "design",
    name: "voice ai platform developer dashboard design system",
    tags: [
      "voice ai",
      "developer dashboard",
      "telephony platform",
      "next.js",
      "tailwind css",
      "dark mode",
      "audio streaming",
      "realtime metrics",
      "api console",
      "fastapi",
      "speech to text",
      "text to speech",
    ],
    points: [
      "Base layout is a dark technical workstation with fixed top navigation, full-bleed ethereal beam canvas backdrops in heroes, and dense 12-column telemetry grids.",
      "Section sequencing moves logically from runtime status and real-time audio pipeline testers down to voice catalogs, per-turn latency breakdowns, and metered API usage tables.",
      "Typography pairs Inter or Geist for neutral interface legibility with JetBrains Mono for hex addresses, stream latencies, token counters, and carrier status logs.",
      "Color palette relies on deep black backgrounds (#090A0F), subtle slate surface cards (#131620), soft borders (#1E2333), crisp white text (#F8FAFC), and sharp cyan (#06B6D4) and emerald (#10B981) status accents.",
      "Spacing maintains a strict 4px modular rhythm with compact 8px cell padding inside telemetry lists and generous 32px to 48px gaps between operational dashboards.",
      "Card surfaces use 8px to 12px corner radii, razor-thin translucent borders (rgba(255, 255, 255, 0.08)), and diffuse low-opacity drop shadows (rgba(0, 0, 0, 0.45)).",
      "Imagery and visual accents are strictly programmatic: dynamic audio waveform visualizers, glowing beam gradients, and live status badges instead of static marketing photography.",
      "Micro-interactions favor smooth page scrolling, instant audio chunk response pulses, and sub-150ms state changes, adhering to prefers-reduced-motion fallbacks.",
    ],
    source: "https://github.com/Prateek22672/voice-ai-platform",
    addedAt: 1791676800000,
    enabled: true,
  },
];
